Modmail Bot Example
Technikstube/discordpy-examples pull request #8
Opened 2024-08-09 12:03 UTC by richard1805-DE

2024-08-09 12:23 UTC, SimplexDE requested changes
Seems to inlcude every channel with a topic, which will cause problems

2024-08-09 12:23 UTC, SimplexDE commented on modmail/cogs/mmsyt.py
> +        if ctx.channel.category and ctx.channel.category.name == "Modmail Tickets": # Change to our Modmail tickets category
Work with an ID here maybe

2024-08-09 12:23 UTC, SimplexDE commented on modmail/cogs/mmsyt.py
> +class MmSyt(commands.Cog):
change the class name to ModmailSystem for better readablity, also rename the file to modmailsystem

remember to change the setup function according to the name change

2024-08-09 12:23 UTC, SimplexDE commented on modmail/cogs/mmsyt.py
> +                    topic = message.channel.topic
This includes every channel with a topic?

2024-08-09 12:26 UTC, Ju0x submitted a review, later dismissed

2024-08-09 12:26 UTC, Ju0x commented on modmail/cogs/mmsyt.py
> +        try:
Use on_error instead of big try/except block

2024-08-09 12:26 UTC, Ju0x commented on modmail/cogs/mmsyt.py
> +class MmSyt(commands.Cog):
Better name for the class

2024-08-09 12:26 UTC, Ju0x commented on modmail/cogs/mmsyt.py
> +                guild = self.bot.get_guild(12321231123) # Change the guild id to your guild id
Use variables at the beginning of the file to find these changeable values better or even a settings.json

2024-08-10 12:01 UTC, SimplexDE approved these changes
👍

2024-08-10 12:02 UTC, merged